# -*- coding: utf-8 -*-
"""Zakaria Rafi_ProyekMLPredictiveAnalytics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eoPOA26loR-mff_AopA5cnjcwkh66Zw_

# Proyek Machine Learning Terapan: PredictiveAnalytics
- Nama: Zakaria Rafi
- Email: zakariarafifahmi@gmail.com
- Id Dicoding:zakaria_rafi

## Domain Proyek

Pada proyek ini, kami berfokus pada analisis dan prediksi jumlah penyewaan sepeda berdasarkan dataset yang menyediakan data historis penyewaan sepeda per jam dan per hari di Washington D.C., AS. Data ini mencakup informasi detil mengenai kondisi cuaca, tanggal, dan jumlah penyewaan sepeda. Tujuan utama kami adalah mengembangkan model yang dapat memprediksi jumlah penyewaan sepeda dengan akurat, yang akan sangat berguna bagi perusahaan penyewaan sepeda untuk mengoptimalkan operasi dan layanan mereka.

## Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

"""Di bagian ini, kita mengimpor library yang diperlukan untuk analisis data, visualisasi, pemodelan, dan evaluasi model.

## Load Dataset
"""

df_hour = pd.read_csv('/content/hour.csv')

"""### Eksplorasi Data"""

print(df_hour.head())

"""### Verifikasi Jumlah Sampel Data"""

total_samples = len(df_hour)
print(f"Total samples: {total_samples}")

"""### Visualisasi Data"""

plt.figure(figsize=(10,6))
sns.histplot(data=df_hour, x='cnt', bins=30, kde=True)

plt.figure(figsize=(12,8))
corr_matrix = df_hour.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")

"""### Pemodelan"""

X = df_hour[['season', 'yr', 'mnth', 'hr', 'holiday', 'weekday', 'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed']]
y = df_hour['cnt']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

"""### Evaluasi Model"""

predictions = model.predict(X_test)
mae = mean_absolute_error(y_test, predictions)
print(f"Mean Absolute Error: {mae}")

"""Model dievaluasi menggunakan metrik Mean Absolute Error (MAE). Tujuannya adalah untuk meminimalkan MAE sehingga model dapat membuat prediksi yang lebih akurat.

### Kesimpulan

### Analisis dan Pemodelan
Proyek ini diarahkan untuk secara spesifik mengkalkulasi dan memprediksi volume penyewaan sepeda di Washington D.C., AS, dengan memperhitungkan variabel lingkungan dan musiman. Dari hasil analisis eksploratif, kami dapat konfirmasi bahwa parameter seperti musim, tahun, bulan, jam, dan kondisi cuaca secara statistik memiliki korelasi yang kuat dan signifikan dengan frekuensi penyewaan sepeda. Kami mengimplementasikan metode Random Forest Regression, yang telah terbukti efektif dalam menghasilkan model prediktif dengan tingkat akurasi yang dapat diandalkan.

### Evaluasi Model
Model ini telah diuji dan dievaluasi dengan menggunakan Mean Absolute Error (MAE) sebagai metrik evaluasinya. MAE menyediakan kajian kuantitatif yang tepat mengenai tingkat kesalahan prediksi model. Walaupun model ini sudah menunjukkan hasil yang memuaskan, kami mengakui adanya potensi untuk optimalisasi lebih lanjut untuk meningkatkan akurasi dan mengurangi kesalahan prediktif.

### Total Sampel Data
Dalam kajian ini, kami telah memastikan bahwa volume sampel data yang digunakan melebihi 500 entri, sehingga memenuhi kriteria statistik dan menjamin keandalan hasil prediksi yang dihasilkan oleh model.

### Optimalisasi dan Penyempurnaan Model
Kami berkomitmen untuk mengoptimalkan model ini melalui proses tuning hyperparameter yang lebih mendalam, eksplorasi algoritma machine learning alternatif, dan metode ensemble untuk memperluas validitas dan keakuratan prediksi. Investigasi fitur tambahan dan implementasi teknik preprocessing data yang lebih sofistikasi juga akan menjadi agenda utama kami dalam upaya penyempurnaan model.

### Implikasi Bisnis
Dalam konteks bisnis, model prediktif yang telah di kembangkan berpotensi menjadi instrumen strategis bagi perusahaan penyewaan sepeda. Dengan memanfaatkan insight yang diberikan model ini, perusahaan dapat merancang strategi operasional dan pemasaran yang lebih efisien, memastikan ketersediaan inventaris sesuai dengan permintaan, mengurangi kelebihan stok, dan secara signifikan meningkatkan kepuasan pelanggan dan rentabilitas bisnis.
"""